all:: 
	g++ -std=c++11 -o SigmaProtocolExample.exe SigmaProtocolExample.cpp -DBOOST_LOG_DYN_LINK=1 ../ScapiCpp/scapi.a -lcrypto -ldl -lOTExtension -lScGarbledCircuitNoFixedKey -lboost_log -lboost_system -lboost_thread -lpthread -maes -mpclmul

clean::
	rm SigmaProtocolExample.exe
	rm SigmaProtocolExample.o



